/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;

import javax.swing.AbstractAction;
import javax.swing.ActionMap;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.KeyStroke;

import modelo.Coordenada;
import modelo.ObjetoGeometrico;
import modelo.RotacionadorArbitrario;
import modelo.RotacionadorSobreOrigem;

/**
 *
 * @author thiago
 */
public class RotacionarDialog extends javax.swing.JDialog {

	/**
	 * A return status code - returned if Cancel button has been pressed
	 */
	public static final int RET_CANCEL = 0;
	/**
	 * A return status code - returned if OK button has been pressed
	 */
	public static final int RET_OK = 1;

	public static final int TAB_ROTACIONAR_PELO_PONTO = 0;
	public static final int TAB_ROTACIONAR_PELA_ORIGEM = 1;

	private ObjetoGeometrico objeto;
	private RotacionadorArbitrario rotacionadorAbitrario;
	private RotacionadorSobreOrigem rotacionadorSobreOrigem;

	/**
	 * Creates new form EscalonarDialog
	 * 
	 * @param objeto
	 */
	public RotacionarDialog(java.awt.Frame parent, boolean modal, ObjetoGeometrico objeto) {
		super(parent, modal);
		this.objeto = objeto;
		initComponents();

		// Close the dialog when Esc is pressed
		String cancelName = "cancel";
		InputMap inputMap = getRootPane().getInputMap(JComponent.WHEN_ANCESTOR_OF_FOCUSED_COMPONENT);
		inputMap.put(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0), cancelName);
		ActionMap actionMap = getRootPane().getActionMap();
		actionMap.put(cancelName, new AbstractAction() {
			@Override
			public void actionPerformed(ActionEvent e) {
				doClose(RET_CANCEL);
			}
		});
	}

	/**
	 * @return the return status of this dialog - one of RET_OK or RET_CANCEL
	 */
	public int getReturnStatus() {
		return returnStatus;
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		okButton = new javax.swing.JButton();
		cancelButton = new javax.swing.JButton();
		painelDeTabs = new javax.swing.JTabbedPane();
		tabOrigem = new javax.swing.JPanel();
		anguloOrigemLabel = new javax.swing.JLabel();
		anguloRotacionarOrigemTextField = new javax.swing.JTextField();
		tabPonto = new javax.swing.JPanel();
		anguloPontoLabel = new javax.swing.JLabel();
		anguloRotacionarPontoTextField = new javax.swing.JTextField();
		painelPonto = new javax.swing.JPanel();
		xLabel = new javax.swing.JLabel();
		pontoXFieldText = new javax.swing.JTextField();
		yLabel = new javax.swing.JLabel();
		pontoYFieldText = new javax.swing.JTextField();

		setTitle("Rotacionar");
		addWindowListener(new java.awt.event.WindowAdapter() {
			@Override
			public void windowClosing(java.awt.event.WindowEvent evt) {
				closeDialog(evt);
			}
		});

		okButton.setText("OK");
		okButton.setToolTipText("Clique para escalonar");
		okButton.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				okButtonActionPerformed(evt);
			}
		});

		cancelButton.setText("Cancel");
		cancelButton.setToolTipText("Clique para cancelar a rotação");
		cancelButton.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				cancelButtonActionPerformed(evt);
			}
		});

		anguloOrigemLabel.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
		anguloOrigemLabel.setText("Ângulo:");

		javax.swing.GroupLayout tabOrigemLayout = new javax.swing.GroupLayout(tabOrigem);
		tabOrigem.setLayout(tabOrigemLayout);
		tabOrigemLayout.setHorizontalGroup(tabOrigemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				tabOrigemLayout.createSequentialGroup().addGap(73, 73, 73).addComponent(anguloOrigemLabel)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(anguloRotacionarOrigemTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(55, Short.MAX_VALUE)));
		tabOrigemLayout.setVerticalGroup(tabOrigemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				tabOrigemLayout
						.createSequentialGroup()
						.addGap(46, 46, 46)
						.addGroup(
								tabOrigemLayout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(anguloOrigemLabel)
										.addComponent(anguloRotacionarOrigemTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)).addContainerGap(48, Short.MAX_VALUE)));

		painelDeTabs.addTab("Rotacionar pela Origem", tabOrigem);

		anguloPontoLabel.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
		anguloPontoLabel.setText("Ângulo:");

		painelPonto.setBorder(javax.swing.BorderFactory.createTitledBorder("Ponto"));

		xLabel.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
		xLabel.setText("X:");

		yLabel.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
		yLabel.setText("Y:");

		javax.swing.GroupLayout painelPontoLayout = new javax.swing.GroupLayout(painelPonto);
		painelPonto.setLayout(painelPontoLayout);
		painelPontoLayout.setHorizontalGroup(painelPontoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				painelPontoLayout.createSequentialGroup().addGap(18, 18, 18).addComponent(xLabel).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(pontoXFieldText, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE).addGap(18, 18, 18)
						.addComponent(yLabel).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(pontoYFieldText, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(38, Short.MAX_VALUE)));
		painelPontoLayout.setVerticalGroup(painelPontoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				painelPontoLayout
						.createSequentialGroup()
						.addGroup(
								painelPontoLayout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(pontoYFieldText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(yLabel)
										.addComponent(pontoXFieldText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE).addComponent(xLabel))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		javax.swing.GroupLayout tabPontoLayout = new javax.swing.GroupLayout(tabPonto);
		tabPonto.setLayout(tabPontoLayout);
		tabPontoLayout.setHorizontalGroup(tabPontoLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						tabPontoLayout.createSequentialGroup().addGap(63, 63, 63).addComponent(anguloPontoLabel)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(anguloRotacionarPontoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
				.addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						tabPontoLayout
								.createSequentialGroup()
								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(painelPonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE).addContainerGap()));
		tabPontoLayout.setVerticalGroup(tabPontoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				tabPontoLayout
						.createSequentialGroup()
						.addGap(17, 17, 17)
						.addGroup(
								tabPontoLayout
										.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
										.addComponent(anguloPontoLabel)
										.addComponent(anguloRotacionarPontoTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(painelPonto, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		painelDeTabs.addTab("Rotacionar através de um Ponto", tabPonto);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(layout.createSequentialGroup().addComponent(painelDeTabs).addContainerGap())
				.addGroup(
						javax.swing.GroupLayout.Alignment.TRAILING,
						layout.createSequentialGroup().addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(cancelButton).addGap(14, 14, 14)));

		layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] { cancelButton, okButton });

		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				layout.createSequentialGroup().addComponent(painelDeTabs, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE).addComponent(okButton).addComponent(cancelButton))
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		getRootPane().setDefaultButton(okButton);

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_okButtonActionPerformed
		boolean semErro = false;
		switch (this.painelDeTabs.getSelectedIndex()) {

		case TAB_ROTACIONAR_PELO_PONTO:
			semErro = rotacionarPeloPonto();
			break;
		case TAB_ROTACIONAR_PELA_ORIGEM:
			semErro = rotacionadorSobreOrigem();
			break;
		}
		if (semErro) {
			doClose(RET_OK);
		}
	}// GEN-LAST:event_okButtonActionPerformed

	private boolean rotacionadorSobreOrigem() {
		return false;
	}

	private boolean rotacionarPeloPonto() {
		boolean semErro = Validador.validarInteiro(anguloRotacionarPontoTextField, anguloPontoLabel);
		semErro &= Validador.validarInteiro(pontoXFieldText, xLabel);
		semErro &= Validador.validarInteiro(pontoYFieldText, yLabel);
		if (semErro) {
			int angulo = Integer.valueOf(this.anguloRotacionarPontoTextField.getText());
			int x = Integer.valueOf(this.pontoXFieldText.getText());
			int y = Integer.valueOf(this.pontoYFieldText.getText());
			Coordenada fatorDeEscala = new Coordenada(x, y);
			rotacionadorAbitrario = new RotacionadorArbitrario(objeto, fatorDeEscala, angulo);
			rotacionadorAbitrario.movimentar();
		}
		return semErro;
	}

	private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_cancelButtonActionPerformed
		doClose(RET_CANCEL);
	}// GEN-LAST:event_cancelButtonActionPerformed

	/**
	 * Closes the dialog
	 */
	private void closeDialog(java.awt.event.WindowEvent evt) {// GEN-FIRST:event_closeDialog
		doClose(RET_CANCEL);
	}// GEN-LAST:event_closeDialog

	private void doClose(int retStatus) {
		returnStatus = retStatus;
		setVisible(false);
		dispose();
	}

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JLabel anguloOrigemLabel;
	private javax.swing.JLabel anguloPontoLabel;
	private javax.swing.JTextField anguloRotacionarOrigemTextField;
	private javax.swing.JTextField anguloRotacionarPontoTextField;
	private javax.swing.JButton cancelButton;
	private javax.swing.JButton okButton;
	private javax.swing.JTabbedPane painelDeTabs;
	private javax.swing.JPanel painelPonto;
	private javax.swing.JTextField pontoXFieldText;
	private javax.swing.JTextField pontoYFieldText;
	private javax.swing.JPanel tabOrigem;
	private javax.swing.JPanel tabPonto;
	private javax.swing.JLabel xLabel;
	private javax.swing.JLabel yLabel;
	// End of variables declaration//GEN-END:variables

	private int returnStatus = RET_CANCEL;
}
