/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.io.File;
import java.io.IOException;
import java.util.List;

import javax.swing.JFileChooser;

import modelo.Direcao;
import modelo.DisplayFile;
import modelo.GravadorDeObj;
import modelo.LeitorDeObj;
import modelo.ObjetoGeometrico;
import modelo.Zoom;

/**
 *
 * @author thiago
 */
public class TelaPrincipal extends javax.swing.JFrame {

	public TelaPrincipal() {
		initComponents();
		repaint();
	}

	public void atualizarPainelDeDesenho() {
		this.painelDeDesenho.repaint();
	}

	public void modificarObjeto(ObjetoGeometrico objetoGeometrico, int indice) {
		listaDeObjetos.remove(indice);
		listaDeObjetos.add(objetoGeometrico.getNome(), indice);
	}

	public void adicionarObjeto(ObjetoGeometrico objetoGeometrico) {
		listaDeObjetos.add(objetoGeometrico.getNome());
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
	// <editor-fold defaultstate="collapsed"
	// <editor-fold defaultstate="collapsed"
	// <editor-fold defaultstate="collapsed"
	// <editor-fold defaultstate="collapsed"
	// <editor-fold defaultstate="collapsed"
	// <editor-fold defaultstate="collapsed"
	// desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {

		painelPrincipal = new javax.swing.JPanel();
		painelDeAcoes = new javax.swing.JPanel();
		painelWindow = new javax.swing.JPanel();
		painelDeZoom = new javax.swing.JPanel();
		botaoZoomIn = new javax.swing.JButton();
		botaoZoomOut = new javax.swing.JButton();
		painelDeNavegacao = new javax.swing.JPanel();
		botaoNavegacaoParaBaixo = new javax.swing.JButton();
		botaoNavegacaoParaCima = new javax.swing.JButton();
		botaoNavegacaoParaDireita = new javax.swing.JButton();
		botaoNavegacaoParaEsquerda = new javax.swing.JButton();
		painelDeObjetos = new javax.swing.JScrollPane();
		listaDeObjetos = new java.awt.List();
		botaoAdicionarObjeto = new javax.swing.JButton();
		botaoRemoverObjeto = new javax.swing.JButton();
		botaoConfigurarObjeto = new javax.swing.JButton();
		painelDeDesenho = new PainelDeDesenho();
		menuBar = new javax.swing.JMenuBar();
		fileMenu = new javax.swing.JMenu();
		importarObjMenuItem = new javax.swing.JMenuItem();
		exportarObjMenuItem = new javax.swing.JMenuItem();
		sairMenuItem = new javax.swing.JMenuItem();
		editMenu = new javax.swing.JMenu();
		adionarFormaMenuItem = new javax.swing.JMenuItem();
		helpMenu = new javax.swing.JMenu();
		sobreMenuItem = new javax.swing.JMenuItem();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("Atividade de Computação Gráfica");
		setResizable(false);
		addHierarchyBoundsListener(new java.awt.event.HierarchyBoundsListener() {
			@Override
			public void ancestorMoved(java.awt.event.HierarchyEvent evt) {
				formAncestorMoved(evt);
			}

			@Override
			public void ancestorResized(java.awt.event.HierarchyEvent evt) {
			}
		});

		painelDeAcoes.setBorder(javax.swing.BorderFactory.createTitledBorder("Menu de Funcoes"));

		painelWindow.setBorder(javax.swing.BorderFactory.createTitledBorder("Window"));
		painelWindow.setToolTipText("Window");

		painelDeZoom.setBorder(javax.swing.BorderFactory.createTitledBorder("Zoom"));
		painelDeZoom.setToolTipText("Painel de Zoom");

		botaoZoomIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imagens/zoom_in.png"))); // NOI18N
		botaoZoomIn.setToolTipText("Zoom in");
		botaoZoomIn.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				botaoZoomInActionPerformed(evt);
			}
		});

		botaoZoomOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imagens/zoom_out.png"))); // NOI18N
		botaoZoomOut.setToolTipText("Zoom out");
		botaoZoomOut.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				botaoZoomOutActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout painelDeZoomLayout = new javax.swing.GroupLayout(painelDeZoom);
		painelDeZoom.setLayout(painelDeZoomLayout);
		painelDeZoomLayout.setHorizontalGroup(painelDeZoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				painelDeZoomLayout.createSequentialGroup().addContainerGap().addComponent(botaoZoomIn, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED).addComponent(botaoZoomOut).addGap(21, 21, 21)));
		painelDeZoomLayout.setVerticalGroup(painelDeZoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				painelDeZoomLayout.createSequentialGroup()
						.addGroup(painelDeZoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(botaoZoomOut).addComponent(botaoZoomIn))
						.addGap(0, 2, Short.MAX_VALUE)));

		painelDeNavegacao.setBorder(javax.swing.BorderFactory.createTitledBorder("Navegação"));
		painelDeNavegacao.setToolTipText("Painel de Navegacao");

		botaoNavegacaoParaBaixo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imagens/seta_baixo.png"))); // NOI18N
		botaoNavegacaoParaBaixo.setToolTipText("Mover para baixo");
		botaoNavegacaoParaBaixo.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				botaoNavegacaoParaBaixoActionPerformed(evt);
			}
		});

		botaoNavegacaoParaCima.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imagens/seta_cima.png"))); // NOI18N
		botaoNavegacaoParaCima.setToolTipText("Mover para cima");
		botaoNavegacaoParaCima.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				botaoNavegacaoParaCimaActionPerformed(evt);
			}
		});

		botaoNavegacaoParaDireita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imagens/seta_direita.png"))); // NOI18N
		botaoNavegacaoParaDireita.setToolTipText("Mover para direita");
		botaoNavegacaoParaDireita.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				botaoNavegacaoParaDireitaActionPerformed(evt);
			}
		});

		botaoNavegacaoParaEsquerda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imagens/seta_esquerda.png"))); // NOI18N
		botaoNavegacaoParaEsquerda.setToolTipText("Mover para esquerda");
		botaoNavegacaoParaEsquerda.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				botaoNavegacaoParaEsquerdaActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout painelDeNavegacaoLayout = new javax.swing.GroupLayout(painelDeNavegacao);
		painelDeNavegacao.setLayout(painelDeNavegacaoLayout);
		painelDeNavegacaoLayout.setHorizontalGroup(painelDeNavegacaoLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						painelDeNavegacaoLayout
								.createSequentialGroup()
								.addGroup(
										painelDeNavegacaoLayout
												.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
												.addGroup(
														painelDeNavegacaoLayout
																.createSequentialGroup()
																.addContainerGap()
																.addComponent(botaoNavegacaoParaEsquerda)
																.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
																		javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE).addComponent(botaoNavegacaoParaDireita))
												.addGroup(
														painelDeNavegacaoLayout.createSequentialGroup().addGap(43, 43, 43).addComponent(botaoNavegacaoParaCima)
																.addGap(0, 0, Short.MAX_VALUE))).addContainerGap())
				.addGroup(
						painelDeNavegacaoLayout.createSequentialGroup().addGap(42, 42, 42).addComponent(botaoNavegacaoParaBaixo)
								.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
		painelDeNavegacaoLayout.setVerticalGroup(painelDeNavegacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				painelDeNavegacaoLayout
						.createSequentialGroup()
						.addComponent(botaoNavegacaoParaCima, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(
								painelDeNavegacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
										.addComponent(botaoNavegacaoParaEsquerda, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
										.addComponent(botaoNavegacaoParaDireita, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(botaoNavegacaoParaBaixo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		javax.swing.GroupLayout painelWindowLayout = new javax.swing.GroupLayout(painelWindow);
		painelWindow.setLayout(painelWindowLayout);
		painelWindowLayout.setHorizontalGroup(painelWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				javax.swing.GroupLayout.Alignment.TRAILING,
				painelWindowLayout
						.createSequentialGroup()
						.addGroup(
								painelWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
										.addComponent(painelDeNavegacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
										.addComponent(painelDeZoom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
						.addContainerGap()));
		painelWindowLayout.setVerticalGroup(painelWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				painelWindowLayout
						.createSequentialGroup()
						.addComponent(painelDeZoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(painelDeNavegacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
								javax.swing.GroupLayout.PREFERRED_SIZE).addGap(0, 213, Short.MAX_VALUE)));

		painelDeObjetos.setBorder(javax.swing.BorderFactory.createTitledBorder("Objetos"));
		painelDeObjetos.setToolTipText("Painel de Objetos");
		painelDeObjetos.setViewportView(listaDeObjetos);

		botaoAdicionarObjeto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imagens/add.png"))); // NOI18N
		botaoAdicionarObjeto.setToolTipText("Adicionar Objeto");
		botaoAdicionarObjeto.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				botaoAdicionarObjetoActionPerformed(evt);
			}
		});

		botaoRemoverObjeto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imagens/remove.png"))); // NOI18N
		botaoRemoverObjeto.setToolTipText("Remover Objeto");
		botaoRemoverObjeto.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				botaoRemoverObjetoActionPerformed(evt);
			}
		});

		botaoConfigurarObjeto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imagens/setting.png"))); // NOI18N
		botaoConfigurarObjeto.setToolTipText("Adicionar Objeto");
		botaoConfigurarObjeto.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				botaoConfigurarObjetoActionPerformed(evt);
			}
		});

		javax.swing.GroupLayout painelDeAcoesLayout = new javax.swing.GroupLayout(painelDeAcoes);
		painelDeAcoes.setLayout(painelDeAcoesLayout);
		painelDeAcoesLayout.setHorizontalGroup(painelDeAcoesLayout
				.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(painelWindow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
				.addComponent(painelDeObjetos, javax.swing.GroupLayout.Alignment.TRAILING)
				.addGroup(
						painelDeAcoesLayout.createSequentialGroup().addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
								.addComponent(botaoConfigurarObjeto).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(botaoAdicionarObjeto).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
								.addComponent(botaoRemoverObjeto).addGap(24, 24, 24)));
		painelDeAcoesLayout.setVerticalGroup(painelDeAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				painelDeAcoesLayout
						.createSequentialGroup()
						.addContainerGap()
						.addComponent(painelDeObjetos, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addGroup(
								painelDeAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(botaoAdicionarObjeto)
										.addComponent(botaoRemoverObjeto).addComponent(botaoConfigurarObjeto))
						.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
						.addComponent(painelWindow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

		painelDeDesenho.setBackground(new java.awt.Color(254, 254, 254));
		painelDeDesenho.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Viewport", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION,
				javax.swing.border.TitledBorder.DEFAULT_POSITION, null, java.awt.Color.darkGray));
		painelDeDesenho.setToolTipText("Viewport");

		javax.swing.GroupLayout painelDeDesenhoLayout = new javax.swing.GroupLayout(painelDeDesenho);
		painelDeDesenho.setLayout(painelDeDesenhoLayout);
		painelDeDesenhoLayout.setHorizontalGroup(painelDeDesenhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 777, Short.MAX_VALUE));
		painelDeDesenhoLayout.setVerticalGroup(painelDeDesenhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGap(0, 0, Short.MAX_VALUE));

		javax.swing.GroupLayout painelPrincipalLayout = new javax.swing.GroupLayout(painelPrincipal);
		painelPrincipal.setLayout(painelPrincipalLayout);
		painelPrincipalLayout.setHorizontalGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addGroup(
						painelPrincipalLayout
								.createSequentialGroup()
								.addComponent(painelDeAcoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
								.addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
								.addComponent(painelDeDesenho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE).addContainerGap()));
		painelPrincipalLayout.setVerticalGroup(painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
				.addComponent(painelDeAcoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
				.addComponent(painelDeDesenho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

		fileMenu.setMnemonic('f');
		fileMenu.setText("Arquivo");

		importarObjMenuItem.setText("Importar Obj");
		importarObjMenuItem.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				importarObjMenuItemActionPerformed(evt);
			}
		});
		fileMenu.add(importarObjMenuItem);

		exportarObjMenuItem.setText("Exportar Obj");
		exportarObjMenuItem.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				exportarObjMenuItemActionPerformed(evt);
			}
		});
		fileMenu.add(exportarObjMenuItem);

		sairMenuItem.setMnemonic('x');
		sairMenuItem.setText("Sair");
		sairMenuItem.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				sairMenuItemActionPerformed(evt);
			}
		});
		fileMenu.add(sairMenuItem);

		menuBar.add(fileMenu);

		editMenu.setMnemonic('e');
		editMenu.setText("Editar");

		adionarFormaMenuItem.setMnemonic('t');
		adionarFormaMenuItem.setText("Adicionar Forma");
		adionarFormaMenuItem.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				adionarFormaMenuItemActionPerformed(evt);
			}
		});
		editMenu.add(adionarFormaMenuItem);

		menuBar.add(editMenu);

		helpMenu.setMnemonic('h');
		helpMenu.setText("Ajuda");

		sobreMenuItem.setMnemonic('a');
		sobreMenuItem.setText("Sobre");
		sobreMenuItem.addActionListener(new java.awt.event.ActionListener() {
			@Override
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				sobreMenuItemActionPerformed(evt);
			}
		});
		helpMenu.add(sobreMenuItem);

		menuBar.add(helpMenu);

		setJMenuBar(menuBar);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
		getContentPane().setLayout(layout);
		layout.setHorizontalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(painelPrincipal,
				javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE));
		layout.setVerticalGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(painelPrincipal,
				javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE));

		pack();
	}// </editor-fold>//GEN-END:initComponents

	private void formAncestorMoved(java.awt.event.HierarchyEvent evt) {// GEN-FIRST:event_formAncestorMoved
		// TODO add your handling code here:
	}// GEN-LAST:event_formAncestorMoved

	private void botaoConfigurarObjetoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_botaoConfigurarObjetoActionPerformed
		int indiceSelecionado = this.listaDeObjetos.getSelectedIndex();
		if (indiceSelecionado != -1) {
			AdicionarFormaDialog edicao = new AdicionarFormaDialog(this, rootPaneCheckingEnabled, true, indiceSelecionado);
			edicao.setLocationRelativeTo(this);
			edicao.setVisible(true);
		}
	}// GEN-LAST:event_botaoConfigurarObjetoActionPerformed

	private void importarObjMenuItemActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_importarObjMenuItemActionPerformed
		final JFileChooser fc = new JFileChooser();
		fc.setDialogTitle("Importar Obj");
		int retorno = fc.showOpenDialog(this);
		if (retorno == JFileChooser.APPROVE_OPTION) {
			File file = fc.getSelectedFile();
			try {
				LeitorDeObj leitorDeObj = new LeitorDeObj(file.getPath());
				List<ObjetoGeometrico> objetosCarregados = leitorDeObj.executar();
				DisplayFile.obterInstancia().iniciarCom(objetosCarregados);
				this.atualizarPainelDeDesenho();
			} catch (IOException e) {

			}
		}
	}// GEN-LAST:event_importarObjMenuItemActionPerformed

	private void exportarObjMenuItemActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_exportarObjMenuItemActionPerformed
		final JFileChooser fc = new JFileChooser();
		fc.setDialogTitle("Exportar Obj");
		int retorno = fc.showSaveDialog(this);
		if (retorno == JFileChooser.APPROVE_OPTION) {
			File file = fc.getSelectedFile();
			try {
				GravadorDeObj leitorDeObj = new GravadorDeObj();
				leitorDeObj.executar(file.getPath(), DisplayFile.obterInstancia().getObjetos());
			} catch (IOException e) {

			}
		}
	}// GEN-LAST:event_exportarObjMenuItemActionPerformed

	private void botaoZoomInActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_botaoZoomInActionPerformed
		this.painelDeDesenho.aplicarZoom(Zoom.IN);
	}// GEN-LAST:event_botaoZoomInActionPerformed

	private void botaoZoomOutActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_botaoZoomOutActionPerformed
		this.painelDeDesenho.aplicarZoom(Zoom.OUT);
	}// GEN-LAST:event_botaoZoomOutActionPerformed

	private void botaoNavegacaoParaCimaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_botaoNavegacaoParaCimaActionPerformed
		this.painelDeDesenho.moverWindow(Direcao.CIMA);
	}// GEN-LAST:event_botaoNavegacaoParaCimaActionPerformed

	private void botaoNavegacaoParaDireitaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_botaoNavegacaoParaDireitaActionPerformed
		this.painelDeDesenho.moverWindow(Direcao.DIREITA);
	}// GEN-LAST:event_botaoNavegacaoParaDireitaActionPerformed

	private void botaoNavegacaoParaBaixoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_botaoNavegacaoParaBaixoActionPerformed
		this.painelDeDesenho.moverWindow(Direcao.BAIXO);
	}// GEN-LAST:event_botaoNavegacaoParaBaixoActionPerformed

	private void botaoNavegacaoParaEsquerdaActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_botaoNavegacaoParaEsquerdaActionPerformed
		this.painelDeDesenho.moverWindow(Direcao.ESQUERDA);
	}// GEN-LAST:event_botaoNavegacaoParaEsquerdaActionPerformed

	private void botaoAdicionarObjetoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_botaoAdicionarObjetoActionPerformed
		AdicionarFormaDialog adicionarFormDialog = new AdicionarFormaDialog(this, rootPaneCheckingEnabled, false, 0);
		adicionarFormDialog.setLocationRelativeTo(this);
		adicionarFormDialog.setVisible(true);
	}// GEN-LAST:event_botaoAdicionarObjetoActionPerformed

	private void botaoRemoverObjetoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_botaoRemoverObjetoActionPerformed
		int indiceSelecionado = this.listaDeObjetos.getSelectedIndex();
		if (indiceSelecionado != -1) {
			this.listaDeObjetos.remove(indiceSelecionado);
			DisplayFile.obterInstancia().remover(indiceSelecionado);
			this.atualizarPainelDeDesenho();
		}
	}// GEN-LAST:event_botaoRemoverObjetoActionPerformed

	private void sairMenuItemActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_sairMenuItemActionPerformed
		System.exit(0);
	}// GEN-LAST:event_sairMenuItemActionPerformed

	private void sobreMenuItemActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_sobreMenuItemActionPerformed
		SobreDialog sobreDialog = new SobreDialog(this, rootPaneCheckingEnabled);
		sobreDialog.setLocationRelativeTo(this);
		sobreDialog.setVisible(true);
	}// GEN-LAST:event_sobreMenuItemActionPerformed

	private void adionarFormaMenuItemActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_adionarFormaMenuItemActionPerformed
		AdicionarFormaDialog adicionarFormDialog = new AdicionarFormaDialog(this, rootPaneCheckingEnabled, false, 0);
		adicionarFormDialog.setLocationRelativeTo(this);
		adicionarFormDialog.setVisible(true);
	}// GEN-LAST:event_adionarFormaMenuItemActionPerformed

	// Variables declaration - do not modify//GEN-BEGIN:variables
	private javax.swing.JMenuItem adionarFormaMenuItem;
	private javax.swing.JButton botaoAdicionarObjeto;
	private javax.swing.JButton botaoConfigurarObjeto;
	private javax.swing.JButton botaoNavegacaoParaBaixo;
	private javax.swing.JButton botaoNavegacaoParaCima;
	private javax.swing.JButton botaoNavegacaoParaDireita;
	private javax.swing.JButton botaoNavegacaoParaEsquerda;
	private javax.swing.JButton botaoRemoverObjeto;
	private javax.swing.JButton botaoZoomIn;
	private javax.swing.JButton botaoZoomOut;
	private javax.swing.JMenu editMenu;
	private javax.swing.JMenuItem exportarObjMenuItem;
	private javax.swing.JMenu fileMenu;
	private javax.swing.JMenu helpMenu;
	private javax.swing.JMenuItem importarObjMenuItem;
	private java.awt.List listaDeObjetos;
	private javax.swing.JMenuBar menuBar;
	private javax.swing.JPanel painelDeAcoes;
	private PainelDeDesenho painelDeDesenho;
	private javax.swing.JPanel painelDeNavegacao;
	private javax.swing.JScrollPane painelDeObjetos;
	private javax.swing.JPanel painelDeZoom;
	private javax.swing.JPanel painelPrincipal;
	private javax.swing.JPanel painelWindow;
	private javax.swing.JMenuItem sairMenuItem;
	private javax.swing.JMenuItem sobreMenuItem;
	// End of variables declaration//GEN-END:variables

}
