/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package view;

import modelo.DisplayFile;

/**
 *
 * @author thiago
 */
public class TelaPrincipal extends javax.swing.JFrame {

    
    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelPrincipal = new javax.swing.JPanel();
        painelDeAcoes = new javax.swing.JPanel();
        painelDeObjetos = new javax.swing.JScrollPane();
        painelWindow = new javax.swing.JPanel();
        painelDeZoom = new javax.swing.JPanel();
        botaoZoomIn = new javax.swing.JButton();
        botaoZoomOut = new javax.swing.JButton();
        painelDeNavegacao = new javax.swing.JPanel();
        botaoNavegacaoParaBaixo = new javax.swing.JButton();
        botaoNavegacaoParaCima = new javax.swing.JButton();
        botaoNavegacaoParaDireita = new javax.swing.JButton();
        botaoNavegacaoParaEsquerda = new javax.swing.JButton();
        painelDeDesenho = new javax.swing.JPanel();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        sairMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        adionarFormaMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        sobreMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Atividade de Computação Gráfica");
        setResizable(false);

        painelDeAcoes.setBorder(javax.swing.BorderFactory.createTitledBorder("Menu de Funcoes"));

        painelDeObjetos.setBorder(javax.swing.BorderFactory.createTitledBorder("Objetos"));
        painelDeObjetos.setToolTipText("Painel de Objetos");

        painelWindow.setBorder(javax.swing.BorderFactory.createTitledBorder("Window"));
        painelWindow.setToolTipText("Window");

        painelDeZoom.setBorder(javax.swing.BorderFactory.createTitledBorder("Zoom"));
        painelDeZoom.setToolTipText("Painel de Zoom");

        botaoZoomIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imagens/zoom_in.png"))); // NOI18N
        botaoZoomIn.setToolTipText("Zoom in");

        botaoZoomOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imagens/zoom_out.png"))); // NOI18N
        botaoZoomOut.setToolTipText("Zoom out");

        javax.swing.GroupLayout painelDeZoomLayout = new javax.swing.GroupLayout(painelDeZoom);
        painelDeZoom.setLayout(painelDeZoomLayout);
        painelDeZoomLayout.setHorizontalGroup(
            painelDeZoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDeZoomLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botaoZoomIn, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botaoZoomOut)
                .addGap(21, 21, 21))
        );
        painelDeZoomLayout.setVerticalGroup(
            painelDeZoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDeZoomLayout.createSequentialGroup()
                .addGroup(painelDeZoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaoZoomOut)
                    .addComponent(botaoZoomIn))
                .addGap(0, 2, Short.MAX_VALUE))
        );

        painelDeNavegacao.setBorder(javax.swing.BorderFactory.createTitledBorder("Navegação"));
        painelDeNavegacao.setToolTipText("Painel de Navegacao");

        botaoNavegacaoParaBaixo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imagens/seta_baixo.png"))); // NOI18N
        botaoNavegacaoParaBaixo.setToolTipText("Mover para baixo");

        botaoNavegacaoParaCima.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imagens/seta_cima.png"))); // NOI18N
        botaoNavegacaoParaCima.setToolTipText("Mover para cima");

        botaoNavegacaoParaDireita.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imagens/seta_direita.png"))); // NOI18N
        botaoNavegacaoParaDireita.setToolTipText("Mover para direita");

        botaoNavegacaoParaEsquerda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/imagens/seta_esquerda.png"))); // NOI18N
        botaoNavegacaoParaEsquerda.setToolTipText("Mover para esquerda");

        javax.swing.GroupLayout painelDeNavegacaoLayout = new javax.swing.GroupLayout(painelDeNavegacao);
        painelDeNavegacao.setLayout(painelDeNavegacaoLayout);
        painelDeNavegacaoLayout.setHorizontalGroup(
            painelDeNavegacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDeNavegacaoLayout.createSequentialGroup()
                .addGroup(painelDeNavegacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelDeNavegacaoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(botaoNavegacaoParaEsquerda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botaoNavegacaoParaDireita))
                    .addGroup(painelDeNavegacaoLayout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(botaoNavegacaoParaCima)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(painelDeNavegacaoLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(botaoNavegacaoParaBaixo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        painelDeNavegacaoLayout.setVerticalGroup(
            painelDeNavegacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelDeNavegacaoLayout.createSequentialGroup()
                .addComponent(botaoNavegacaoParaCima, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(painelDeNavegacaoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botaoNavegacaoParaEsquerda, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botaoNavegacaoParaDireita, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoNavegacaoParaBaixo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout painelWindowLayout = new javax.swing.GroupLayout(painelWindow);
        painelWindow.setLayout(painelWindowLayout);
        painelWindowLayout.setHorizontalGroup(
            painelWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelWindowLayout.createSequentialGroup()
                .addGroup(painelWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(painelDeNavegacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(painelDeZoom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        painelWindowLayout.setVerticalGroup(
            painelWindowLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelWindowLayout.createSequentialGroup()
                .addComponent(painelDeZoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelDeNavegacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 201, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout painelDeAcoesLayout = new javax.swing.GroupLayout(painelDeAcoes);
        painelDeAcoes.setLayout(painelDeAcoesLayout);
        painelDeAcoesLayout.setHorizontalGroup(
            painelDeAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelDeObjetos)
            .addComponent(painelWindow, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        painelDeAcoesLayout.setVerticalGroup(
            painelDeAcoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelDeAcoesLayout.createSequentialGroup()
                .addComponent(painelDeObjetos, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(painelWindow, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        painelDeDesenho.setBackground(new java.awt.Color(254, 254, 254));
        painelDeDesenho.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Viewport", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, java.awt.Color.darkGray));
        painelDeDesenho.setToolTipText("Viewport");

        javax.swing.GroupLayout painelDeDesenhoLayout = new javax.swing.GroupLayout(painelDeDesenho);
        painelDeDesenho.setLayout(painelDeDesenhoLayout);
        painelDeDesenhoLayout.setHorizontalGroup(
            painelDeDesenhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 777, Short.MAX_VALUE)
        );
        painelDeDesenhoLayout.setVerticalGroup(
            painelDeDesenhoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout painelPrincipalLayout = new javax.swing.GroupLayout(painelPrincipal);
        painelPrincipal.setLayout(painelPrincipalLayout);
        painelPrincipalLayout.setHorizontalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelPrincipalLayout.createSequentialGroup()
                .addComponent(painelDeAcoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(painelDeDesenho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        painelPrincipalLayout.setVerticalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelDeAcoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(painelDeDesenho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        fileMenu.setMnemonic('f');
        fileMenu.setText("Arquivo");

        sairMenuItem.setMnemonic('x');
        sairMenuItem.setText("Sair");
        sairMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sairMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(sairMenuItem);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Editar");

        adionarFormaMenuItem.setMnemonic('t');
        adionarFormaMenuItem.setText("Adicionar Forma");
        adionarFormaMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adionarFormaMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(adionarFormaMenuItem);

        menuBar.add(editMenu);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Ajuda");

        sobreMenuItem.setMnemonic('a');
        sobreMenuItem.setText("Sobre");
        sobreMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sobreMenuItemActionPerformed(evt);
            }
        });
        helpMenu.add(sobreMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sairMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sairMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_sairMenuItemActionPerformed

    private void sobreMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sobreMenuItemActionPerformed
        SobreDialog sobreDialog = new SobreDialog(this, rootPaneCheckingEnabled);
        sobreDialog.setLocationRelativeTo(this);
        sobreDialog.setVisible(true);
    }//GEN-LAST:event_sobreMenuItemActionPerformed

    private void adionarFormaMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adionarFormaMenuItemActionPerformed
       AdicionarFormaDialog adicionarFormDialog = new AdicionarFormaDialog(this, rootPaneCheckingEnabled);
       adicionarFormDialog.setLocationRelativeTo(this);
       adicionarFormDialog.setVisible(true);
    }//GEN-LAST:event_adionarFormaMenuItemActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem adionarFormaMenuItem;
    private javax.swing.JButton botaoNavegacaoParaBaixo;
    private javax.swing.JButton botaoNavegacaoParaCima;
    private javax.swing.JButton botaoNavegacaoParaDireita;
    private javax.swing.JButton botaoNavegacaoParaEsquerda;
    private javax.swing.JButton botaoZoomIn;
    private javax.swing.JButton botaoZoomOut;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JPanel painelDeAcoes;
    private javax.swing.JPanel painelDeDesenho;
    private javax.swing.JPanel painelDeNavegacao;
    private javax.swing.JScrollPane painelDeObjetos;
    private javax.swing.JPanel painelDeZoom;
    private javax.swing.JPanel painelPrincipal;
    private javax.swing.JPanel painelWindow;
    private javax.swing.JMenuItem sairMenuItem;
    private javax.swing.JMenuItem sobreMenuItem;
    // End of variables declaration//GEN-END:variables

}
